# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4040d042bf6477783b14557e25ae20e0c7d71313241bd8f1360f85de75c8349175aa217c1120fb59ae315cc0606bd1f8ef5f54f16d89dc54b4b457b1679cffc7

test:
  secret_key_base: 4dc3b40a4a2f0fe50627325eb0145ff4e8f28a615bd5d00f8ec5571a28daa9b6fc8f17ae7ac0a6315c28d826d1a52876b04e68a71ca1e0cd03474eddf18c8cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
